export const playersData = [
  {
    id: "lebron-james",
    name: "LeBron James",
    team: "Los Angeles Lakers",
    position: "Forward",
    jerseyNumber: 23,
    height: "6'9\"",
    weight: "250 lbs",
    age: 39,
    experience: 21,
    college: "St. Vincent-St. Mary HS (OH)",
    draft: "2003 R1 Pick 1",
    imageSrc: "/placeholder.svg?height=300&width=300",
    bio: "LeBron James is an American professional basketball player for the Los Angeles Lakers of the NBA. Nicknamed 'King James', he is widely considered one of the greatest players of all time.",
    extendedBio:
      "James has won four NBA championships, four NBA MVP awards, four NBA Finals MVP awards, and two Olympic gold medals. He has competed in ten NBA Finals, the third most all-time, including eight consecutive with the Heat and Cavaliers from 2011 through 2018.",
    careerHighlights: [
      "4× NBA champion (2012, 2013, 2016, 2020)",
      "4× NBA Finals MVP (2012, 2013, 2016, 2020)",
      "4× NBA Most Valuable Player (2009, 2010, 2012, 2013)",
      "19× NBA All-Star (2005–2023)",
      "3× NBA All-Star Game MVP (2006, 2008, 2018)",
      "NBA's all-time leading scorer",
    ],
    stats: {
      points: 27.3,
      rebounds: 7.4,
      assists: 8.3,
      steals: 1.3,
      blocks: 0.8,
      fieldGoalPercentage: 0.504,
      threePointPercentage: 0.345,
      freeThrowPercentage: 0.734,
      minutes: 35.2,
      gamesPlayed: 82,
    },
    careerStats: [
      {
        season: "2022-23",
        team: "LAL",
        gamesPlayed: 55,
        minutes: 35.5,
        points: 28.9,
        rebounds: 8.3,
        assists: 6.8,
        steals: 0.9,
        blocks: 0.6,
        fieldGoalPercentage: 0.5,
        threePointPercentage: 0.321,
        freeThrowPercentage: 0.761,
      },
      {
        season: "2021-22",
        team: "LAL",
        gamesPlayed: 56,
        minutes: 37.2,
        points: 30.3,
        rebounds: 8.2,
        assists: 6.2,
        steals: 1.3,
        blocks: 1.1,
        fieldGoalPercentage: 0.524,
        threePointPercentage: 0.359,
        freeThrowPercentage: 0.756,
      },
      {
        season: "2020-21",
        team: "LAL",
        gamesPlayed: 45,
        minutes: 33.4,
        points: 25.0,
        rebounds: 7.7,
        assists: 7.8,
        steals: 1.1,
        blocks: 0.6,
        fieldGoalPercentage: 0.513,
        threePointPercentage: 0.365,
        freeThrowPercentage: 0.698,
      },
    ],
    recentGames: [
      {
        date: "Mar 16, 2023",
        opponent: "HOU",
        result: "W",
        score: "130-125",
        minutes: 38,
        points: 32,
        rebounds: 11,
        assists: 6,
        steals: 1,
        blocks: 0,
        fieldGoals: "11-21",
        threePointers: "2-5",
        freeThrows: "8-9",
      },
      {
        date: "Mar 14, 2023",
        opponent: "MEM",
        result: "L",
        score: "112-123",
        minutes: 36,
        points: 26,
        rebounds: 7,
        assists: 5,
        steals: 0,
        blocks: 1,
        fieldGoals: "10-19",
        threePointers: "1-5",
        freeThrows: "5-6",
      },
      {
        date: "Mar 12, 2023",
        opponent: "NYK",
        result: "W",
        score: "112-105",
        minutes: 40,
        points: 28,
        rebounds: 10,
        assists: 11,
        steals: 1,
        blocks: 0,
        fieldGoals: "10-21",
        threePointers: "2-8",
        freeThrows: "6-8",
      },
    ],
  },
  {
    id: "kevin-durant",
    name: "Kevin Durant",
    team: "Phoenix Suns",
    position: "Forward",
    jerseyNumber: 35,
    height: "6'10\"",
    weight: "240 lbs",
    age: 35,
    experience: 16,
    college: "Texas",
    draft: "2007 R1 Pick 2",
    imageSrc: "/placeholder.svg?height=300&width=300",
    bio: "Kevin Durant is an American professional basketball player for the Phoenix Suns of the NBA. He is widely regarded as one of the greatest scorers and players of all time.",
    extendedBio:
      "Durant has won two NBA championships, an NBA Most Valuable Player Award, two Finals MVP Awards, and two Olympic gold medals. He has also been selected for 13 All-Star games and has four NBA scoring titles.",
    careerHighlights: [
      "2× NBA champion (2017, 2018)",
      "2× NBA Finals MVP (2017, 2018)",
      "NBA Most Valuable Player (2014)",
      "13× NBA All-Star (2010–2019, 2021–2023)",
      "6× All-NBA First Team (2010–2014, 2018)",
      "4× NBA scoring champion (2010–2012, 2014)",
    ],
    stats: {
      points: 29.1,
      rebounds: 6.7,
      assists: 5.0,
      steals: 0.7,
      blocks: 1.1,
      fieldGoalPercentage: 0.559,
      threePointPercentage: 0.401,
      freeThrowPercentage: 0.919,
      minutes: 34.6,
      gamesPlayed: 47,
    },
    careerStats: [
      {
        season: "2022-23",
        team: "BKN/PHX",
        gamesPlayed: 47,
        minutes: 34.6,
        points: 29.1,
        rebounds: 6.7,
        assists: 5.0,
        steals: 0.7,
        blocks: 1.1,
        fieldGoalPercentage: 0.559,
        threePointPercentage: 0.401,
        freeThrowPercentage: 0.919,
      },
      {
        season: "2021-22",
        team: "BKN",
        gamesPlayed: 55,
        minutes: 37.2,
        points: 29.9,
        rebounds: 7.4,
        assists: 6.4,
        steals: 0.9,
        blocks: 0.9,
        fieldGoalPercentage: 0.518,
        threePointPercentage: 0.383,
        freeThrowPercentage: 0.91,
      },
      {
        season: "2020-21",
        team: "BKN",
        gamesPlayed: 35,
        minutes: 33.1,
        points: 26.9,
        rebounds: 7.1,
        assists: 5.6,
        steals: 0.7,
        blocks: 1.3,
        fieldGoalPercentage: 0.537,
        threePointPercentage: 0.45,
        freeThrowPercentage: 0.887,
      },
    ],
    recentGames: [
      {
        date: "Mar 16, 2023",
        opponent: "ORL",
        result: "W",
        score: "116-113",
        minutes: 36,
        points: 35,
        rebounds: 6,
        assists: 4,
        steals: 0,
        blocks: 2,
        fieldGoals: "12-21",
        threePointers: "3-5",
        freeThrows: "8-8",
      },
      {
        date: "Mar 14, 2023",
        opponent: "MIL",
        result: "L",
        score: "116-104",
        minutes: 37,
        points: 26,
        rebounds: 6,
        assists: 7,
        steals: 1,
        blocks: 1,
        fieldGoals: "8-17",
        threePointers: "2-4",
        freeThrows: "8-9",
      },
      {
        date: "Mar 11, 2023",
        opponent: "SAC",
        result: "W",
        score: "128-119",
        minutes: 39,
        points: 31,
        rebounds: 8,
        assists: 7,
        steals: 0,
        blocks: 1,
        fieldGoals: "10-18",
        threePointers: "3-7",
        freeThrows: "8-8",
      },
    ],
  },
  {
    id: "stephen-curry",
    name: "Stephen Curry",
    team: "Golden State Warriors",
    position: "Guard",
    jerseyNumber: 30,
    height: "6'2\"",
    weight: "185 lbs",
    age: 35,
    experience: 14,
    college: "Davidson",
    draft: "2009 R1 Pick 7",
    imageSrc: "/placeholder.svg?height=300&width=300",
    bio: "Stephen Curry is an American professional basketball player for the Golden State Warriors of the NBA. He is widely regarded as one of the greatest basketball players of all time, and the greatest shooter in NBA history.",
    extendedBio:
      "Curry is credited with revolutionizing the game of basketball by inspiring teams and players to take more three-point shots. He has won four NBA championships, two NBA Most Valuable Player (MVP) awards, and an NBA Finals MVP award.",
    careerHighlights: [
      "4× NBA champion (2015, 2017, 2018, 2022)",
      "NBA Finals MVP (2022)",
      "2× NBA Most Valuable Player (2015, 2016)",
      "9× NBA All-Star (2014–2019, 2021–2023)",
      "NBA All-Star Game MVP (2022)",
      "NBA's all-time leader in three-pointers made",
    ],
    stats: {
      points: 29.4,
      rebounds: 6.1,
      assists: 6.3,
      steals: 0.9,
      blocks: 0.2,
      fieldGoalPercentage: 0.493,
      threePointPercentage: 0.429,
      freeThrowPercentage: 0.915,
      minutes: 34.7,
      gamesPlayed: 56,
    },
    careerStats: [
      {
        season: "2022-23",
        team: "GSW",
        gamesPlayed: 56,
        minutes: 34.7,
        points: 29.4,
        rebounds: 6.1,
        assists: 6.3,
        steals: 0.9,
        blocks: 0.2,
        fieldGoalPercentage: 0.493,
        threePointPercentage: 0.429,
        freeThrowPercentage: 0.915,
      },
      {
        season: "2021-22",
        team: "GSW",
        gamesPlayed: 64,
        minutes: 34.5,
        points: 25.5,
        rebounds: 5.2,
        assists: 6.3,
        steals: 1.3,
        blocks: 0.4,
        fieldGoalPercentage: 0.437,
        threePointPercentage: 0.38,
        freeThrowPercentage: 0.923,
      },
      {
        season: "2020-21",
        team: "GSW",
        gamesPlayed: 63,
        minutes: 34.2,
        points: 32.0,
        rebounds: 5.5,
        assists: 5.8,
        steals: 1.2,
        blocks: 0.1,
        fieldGoalPercentage: 0.482,
        threePointPercentage: 0.421,
        freeThrowPercentage: 0.916,
      },
    ],
    recentGames: [
      {
        date: "Mar 15, 2023",
        opponent: "LAC",
        result: "W",
        score: "115-91",
        minutes: 31,
        points: 29,
        rebounds: 4,
        assists: 7,
        steals: 1,
        blocks: 0,
        fieldGoals: "10-16",
        threePointers: "4-10",
        freeThrows: "5-5",
      },
      {
        date: "Mar 13, 2023",
        opponent: "PHX",
        result: "L",
        score: "123-112",
        minutes: 37,
        points: 28,
        rebounds: 7,
        assists: 5,
        steals: 0,
        blocks: 0,
        fieldGoals: "9-20",
        threePointers: "6-11",
        freeThrows: "4-4",
      },
      {
        date: "Mar 11, 2023",
        opponent: "MIL",
        result: "W",
        score: "125-116",
        minutes: 38,
        points: 36,
        rebounds: 6,
        assists: 4,
        steals: 2,
        blocks: 0,
        fieldGoals: "13-27",
        threePointers: "6-15",
        freeThrows: "4-4",
      },
    ],
  },
  {
    id: "giannis-antetokounmpo",
    name: "Giannis Antetokounmpo",
    team: "Milwaukee Bucks",
    position: "Forward",
    jerseyNumber: 34,
    height: "6'11\"",
    weight: "242 lbs",
    age: 28,
    experience: 10,
    college: "Greece",
    draft: "2013 R1 Pick 15",
    imageSrc: "/placeholder.svg?height=300&width=300",
    bio: "Giannis Antetokounmpo is a Greek professional basketball player for the Milwaukee Bucks of the NBA. His combination of size, speed, and ball-handling skills earned him the nickname 'Greek Freak'.",
    extendedBio:
      "Antetokounmpo led the Bucks to their first NBA championship since 1971 in 2021, and was named Finals MVP. He is a two-time NBA Most Valuable Player and has been selected to seven All-Star teams.",
    careerHighlights: [
      "NBA champion (2021)",
      "NBA Finals MVP (2021)",
      "2× NBA Most Valuable Player (2019, 2020)",
      "7× NBA All-Star (2017–2023)",
      "NBA Defensive Player of the Year (2020)",
      "NBA Most Improved Player (2017)",
    ],
    stats: {
      points: 31.1,
      rebounds: 11.8,
      assists: 5.6,
      steals: 0.8,
      blocks: 0.8,
      fieldGoalPercentage: 0.553,
      threePointPercentage: 0.277,
      freeThrowPercentage: 0.645,
      minutes: 32.1,
      gamesPlayed: 63,
    },
    careerStats: [
      {
        season: "2022-23",
        team: "MIL",
        gamesPlayed: 63,
        minutes: 32.1,
        points: 31.1,
        rebounds: 11.8,
        assists: 5.6,
        steals: 0.8,
        blocks: 0.8,
        fieldGoalPercentage: 0.553,
        threePointPercentage: 0.277,
        freeThrowPercentage: 0.645,
      },
      {
        season: "2021-22",
        team: "MIL",
        gamesPlayed: 67,
        minutes: 32.9,
        points: 29.9,
        rebounds: 11.6,
        assists: 5.8,
        steals: 1.1,
        blocks: 1.4,
        fieldGoalPercentage: 0.553,
        threePointPercentage: 0.293,
        freeThrowPercentage: 0.722,
      },
      {
        season: "2020-21",
        team: "MIL",
        gamesPlayed: 61,
        minutes: 33.0,
        points: 28.1,
        rebounds: 11.0,
        assists: 5.9,
        steals: 1.2,
        blocks: 1.2,
        fieldGoalPercentage: 0.569,
        threePointPercentage: 0.303,
        freeThrowPercentage: 0.685,
      },
    ],
    recentGames: [
      {
        date: "Mar 16, 2023",
        opponent: "IND",
        result: "W",
        score: "139-123",
        minutes: 33,
        points: 38,
        rebounds: 13,
        assists: 5,
        steals: 0,
        blocks: 1,
        fieldGoals: "14-18",
        threePointers: "0-2",
        freeThrows: "10-14",
      },
      {
        date: "Mar 14, 2023",
        opponent: "PHX",
        result: "W",
        score: "116-104",
        minutes: 36,
        points: 36,
        rebounds: 11,
        assists: 8,
        steals: 1,
        blocks: 0,
        fieldGoals: "15-24",
        threePointers: "1-3",
        freeThrows: "5-9",
      },
      {
        date: "Mar 11, 2023",
        opponent: "GSW",
        result: "L",
        score: "125-116",
        minutes: 39,
        points: 31,
        rebounds: 12,
        assists: 5,
        steals: 1,
        blocks: 1,
        fieldGoals: "10-21",
        threePointers: "0-2",
        freeThrows: "11-17",
      },
    ],
  },
]

export const teamsData = [
  {
    id: "lakers",
    name: "Los Angeles Lakers",
    conference: "Western",
    division: "Pacific",
    founded: 1947,
    location: "Los Angeles, California",
    arena: "Crypto.com Arena",
    colors: "Purple and Gold",
    logoSrc: "/placeholder.svg?height=200&width=200",
    record: "40-38",
    standing: "7th",
    headCoach: "Darvin Ham",
    championships: 17,
    website: "https://www.nba.com/lakers/",
  },
  {
    id: "celtics",
    name: "Boston Celtics",
    conference: "Eastern",
    division: "Atlantic",
    founded: 1946,
    location: "Boston, Massachusetts",
    arena: "TD Garden",
    colors: "Green and White",
    logoSrc: "/placeholder.svg?height=200&width=200",
    record: "54-24",
    standing: "2nd",
    headCoach: "Joe Mazzulla",
    championships: 17,
    website: "https://www.nba.com/celtics/",
  },
  {
    id: "warriors",
    name: "Golden State Warriors",
    conference: "Western",
    division: "Pacific",
    founded: 1946,
    location: "San Francisco, California",
    arena: "Chase Center",
    colors: "Royal Blue and Golden Yellow",
    logoSrc: "/placeholder.svg?height=200&width=200",
    record: "41-37",
    standing: "6th",
    headCoach: "Steve Kerr",
    championships: 7,
    website: "https://www.nba.com/warriors/",
  },
  {
    id: "bucks",
    name: "Milwaukee Bucks",
    conference: "Eastern",
    division: "Central",
    founded: 1968,
    location: "Milwaukee, Wisconsin",
    arena: "Fiserv Forum",
    colors: "Green, Cream, and Blue",
    logoSrc: "/placeholder.svg?height=200&width=200",
    record: "55-22",
    standing: "1st",
    headCoach: "Mike Budenholzer",
    championships: 2,
    website: "https://www.nba.com/bucks/",
  },
  {
    id: "suns",
    name: "Phoenix Suns",
    conference: "Western",
    division: "Pacific",
    founded: 1968,
    location: "Phoenix, Arizona",
    arena: "Footprint Center",
    colors: "Purple, Orange, and Black",
    logoSrc: "/placeholder.svg?height=200&width=200",
    record: "41-36",
    standing: "4th",
    headCoach: "Monty Williams",
    championships: 0,
    website: "https://www.nba.com/suns/",
  },
  {
    id: "nets",
    name: "Brooklyn Nets",
    conference: "Eastern",
    division: "Atlantic",
    founded: 1967,
    location: "Brooklyn, New York",
    arena: "Barclays Center",
    colors: "Black and White",
    logoSrc: "/placeholder.svg?height=200&width=200",
    record: "42-36",
    standing: "6th",
    headCoach: "Jacque Vaughn",
    championships: 0,
    website: "https://www.nba.com/nets/",
  },
  {
    id: "nuggets",
    name: "Denver Nuggets",
    conference: "Western",
    division: "Northwest",
    founded: 1967,
    location: "Denver, Colorado",
    arena: "Ball Arena",
    colors: "Navy Blue, Gold, and Red",
    logoSrc: "/placeholder.svg?height=200&width=200",
    record: "51-26",
    standing: "1st",
    headCoach: "Michael Malone",
    championships: 0,
    website: "https://www.nba.com/nuggets/",
  },
  {
    id: "heat",
    name: "Miami Heat",
    conference: "Eastern",
    division: "Southeast",
    founded: 1988,
    location: "Miami, Florida",
    arena: "FTX Arena",
    colors: "Red, Black, and White",
    logoSrc: "/placeholder.svg?height=200&width=200",
    record: "41-37",
    standing: "7th",
    headCoach: "Erik Spoelstra",
    championships: 3,
    website: "https://www.nba.com/heat/",
  },
]

